# For more information: https://laravel.com/docs/sail
version: "3"
services:
    laravel.test:
        image: tangramor/nginx-php8-fpm
        environment:
            TZ: "America/Lima"
            WEBROOT: "/var/www/html/public"
            PHP_REDIS_SESSION_HOST: "redis"
            CREATE_LARAVEL_STORAGE: "1"
            COMPOSERMIRROR: "https://mirrors.cloud.tencent.com/composer/"
            NPMMIRROR: "https://registry.npmmirror.com"
        ports:
            - "${APP_PORT:-90}:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail

networks:
    sail:
        driver: bridge
